/* Automatically generated by po2tbl.sed from project1.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"window1", 2},
  {"label1", 3},
  {"button1", 4},
  {"dialog1", 5},
  {"Couldn't find pixmap file: %s", 6},
  {"Couldn't create pixmap from file: %s", 7},
};

int _msg_tbl_length = 7;
